"""empty message

Revision ID: 6b92afa3be7e
Revises: cbb77fde5580
Create Date: 2021-03-08 19:26:30.095054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b92afa3be7e'
down_revision = 'cbb77fde5580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('uri', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'recipe', ['uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    op.drop_column('recipe', 'uri')
    # ### end Alembic commands ###
