"""empty message

Revision ID: c7c9060f3605
Revises: 651d0f088e63
Create Date: 2021-04-18 17:21:54.318219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c9060f3605'
down_revision = '651d0f088e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selected_recipe', sa.Column('recipe_label', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selected_recipe', 'recipe_label')
    # ### end Alembic commands ###
